export const GET_NEWS_API = 'GET_NEWS_API';
export const GET_NEWS_API_SUCCESS = 'GET_NEWS_API_SUCCESS';
export const GET_NEWS_API_ERROR = 'GET_NEWS_API_ERROR';

export const FETCH_NEWS_API_ORG = 'FETCH_NEWS_API_ORG';
export const FETCH_NEWS_API_ORG_SUCCESS = 'FETCH_NEWS_API_ORG_SUCCESS';
export const FETCH_NEWS_API_ORG_ERROR = 'FETCH_NEWS_API_ORG_ERROR';