export const GET_STOCK_INFO = 'GET_STOCK_INFO';
export const GET_STOCK_INFO_SUCCESS = 'GET_STOCK_INFO_SUCCESS';
export const GET_STOCK_INFO_ERROR = 'GET_STOCK_INFO_ERROR';

export const GET_STOCK_FINANCIAL = 'GET_STOCK_FINANCIAL';
export const GET_STOCK_FINANCIAL_SUCCESS = 'GET_STOCK_FINANCIAL_SUCCESS';
export const GET_STOCK_FINANCIAL_ERROR = 'GET_STOCK_FINANCIAL_ERROR';